version: '3.3'
name: askfinance-api-1
services:
  db:
    image: postgres:15-alpine
    container_name: a-askfinance-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Colombo
      - PGTZ=Asia/Colombo
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - net

  migrations:
    build: migrations
    container_name: a-askfinance-migrations
    command: -connectRetries=20 migrate
    environment:
      FLYWAY_USER: 'postgres'
      FLYWAY_MIXED: 'true'
      FLYWAY_PASSWORD: 'postgres'
      FLYWAY_URL: 'jdbc:postgresql://db:5432/postgres'
    networks:
      - net

  vector-db:
    image: qdrant/qdrant
    container_name: a-askfinance-vector-db
    restart: always
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - net

volumes:
  db:
    driver: local
  qdrant_data:
    driver: local


networks:
  net:
    driver: bridge
