CREATE TABLE IF NOT EXISTS api_token (
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    deactivated BOOLEAN DEFAULT FALSE,
    origin VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);